const fs = require('fs');
const path = require('path');

function genExportFile() {
  const fileDescription = '// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n\n';
  const contents = [];
  const rootDir = path.resolve(__dirname, '../src');
  const outputFile = path.join(rootDir, 'index.ts');

  walker(rootDir);

  function walker(dir, prefix = '') {
    const files = fs.readdirSync(dir, { withFileTypes: true });
    files.forEach(file => {
      const name = file.name;

      const isDirectory = file.isDirectory();
      if (isDirectory) {
        // 如果是空文件则跳过
        if (isEmptyDir(path.join(dir, name))) {
          return;
        }
        // 如果是private文件夹则跳过
        if (name === 'private') {
          return;
        }

        walker(path.join(dir, name), prefix + name + '/');
        return;
      }

      const filename = name.replace(/\.ts(x)?$/, '');
      if (name !== 'index.ts') {
        let code = prefix !== '' ? `export * from \'./${prefix}${filename}\';` : `export * from \'./${filename}\';`;
        contents.push(code);
      }
    });
  }

  fs.writeFileSync(outputFile, fileDescription + contents.join('\n'), 'utf8');
  fs.appendFileSync(outputFile, '\n');
}

function isEmptyDir(path) {
  return fs.readdirSync(path).length === 0;
}

module.exports = genExportFile;
