export enum FE {
  GET_STORAGE = 'FIGMA_EVENT_GET_STORAGE', // 从插件获取存储
  DOCUMENT_CHANGE = 'FIGMA_EVENT_DOCUMENT_CHANGE', // 文档改变
  NODE_CHANGE = 'FIGMA_EVENT_NODE_CHANGE', // 节点改变
  SHOW_NOTIFY = 'FIGMA_EVENT_SHOW_NOTIFY', // 显示消息
  SELECTION_CHANGE = 'FIGMA_EVENT_SELECTION_CHANGE',
  GET_USED_FONTS = 'FIGMA_EVENT_GET_USED_FONTS', // 获取使用的字体
  GET_AVAILABLE_FONTS = 'FIGMA_EVENT_GET_AVAILABLE_FONTS', // 获取所有可用字体
}

export enum UE {
  GET_STORAGE = 'USER_EVENT_GET_STORAGE',
  SET_STORAGE = 'USER_EVENT_SET_STORAGE', // 设置插件存储
  GET_USED_FONTS = 'USER_EVENT_GET_USED_FONTS', // 获取使用的字体
  GET_AVAILABLE_FONTS = 'FIGMA_EVENT_GET_AVAILABLE_FONTS', // 获取所有可用字体
  RESIZE_UI = 'FIGMA_EVENT_RESIZE_UI', // 调整插件窗口大小
}
